// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCePpfo8rQ57UEvWKA3fjvpp_I9-PNgtIA',
    appId: '1:949529044701:web:291f3880fe73c483615d34',
    messagingSenderId: '949529044701',
    projectId: 'bajaj-updated',
    authDomain: 'bajaj-updated.firebaseapp.com',
    storageBucket: 'bajaj-updated.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sNHx9wdT9wHV41JBFJCIjBDZxJnPjmI',
    appId: '1:949529044701:android:ccafa7bd7b89d0cb615d34',
    messagingSenderId: '949529044701',
    projectId: 'bajaj-updated',
    storageBucket: 'bajaj-updated.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-WrtWNhXbwerPs0tU6sbbl9mg1FpPXU',
    appId: '1:949529044701:ios:3847830d8de24d97615d34',
    messagingSenderId: '949529044701',
    projectId: 'bajaj-updated',
    storageBucket: 'bajaj-updated.firebasestorage.app',
    iosBundleId: 'com.example.bajaj',
  );
}
